### ISSUE TITLE
related packages

### ISSUE THREAD

**Issue by timotheecour** [AndreiRegiani/INim#4]
* how would this compare to https://github.com/wheineman/nrpl ? **EDIT** some of ideas in nrpl could be borrowed in inim

**EDIT**

* https://github.com/jlp765/tnim TinyNim - a REPL for Nim (an interactive sandbox for testing Nim code)

**Comment by juancarlospaco** [comment]
The other package is dead, last update 2015.

**Comment by AndreiRegiani** [comment]
Both are indeed similar. Now INim has some better features (see updated README.md, though the GIF is outdated). I plan to keep adding/accepting more features to INim, such as auto-complete, to get to the level of `bpython3`. `nrpl` depends on TCC [http://bellard.org/tcc/], so doesn't work out of the box.

**Comment by timotheecour** [comment]
> to get to the level of bpython3

you probably be already know but ipython is some good features not present in bpython (and there's a combo bipython that combines both...)

**Comment by AndreiRegiani** [comment]
There is also the official REPL `nim secret` (seems to work as an interpreter which is limited[1], instead of re-compilation) but it has many problems [1] so it's hidden from the users and won't be documented [2].
```
$ nim secret
```

[1] https://github.com/nim-lang/Nim/issues/5886
[2] https://github.com/nim-lang/Nim/issues/2633

---


`tnim` (not the website) seems way more bugged than INim for REPL usage, after messing up with the indentation I got errors afterwards (invalid indentation), closing and opening again didn't fix, had to clear my session with `\quitclear`, this behavior is not expected for a python-like REPL.

It looks like INim is the best out there.
